// JAVASCRIPT IS A SINGLE THREADED LANGUAGE, SO IT CAN ONLY RUN ONE TASK AT A TIME. THIS IS KNOWN AS A GLOBAL LOCK. 
// THIS MEANS THAT IF YOU ARE DOING CPU-INTENSIVE TASKS, YOU WILL BE BLOCKING THE EVENT LOOP AND PREVENTING OTHER TASKS FROM RUNNING. 
// THIS IS KNOWN AS A DEADLOCK.


// JAVASCRIPT IS A SYNCHRONOUS LANGUAGE, SO IT WILL WAIT FOR A TASK TO COMPLETE BEFORE MOVING ON TO THE NEXT ONE.   

console.log(1);
setTimeout(() => {
    console.log(2); // THIS WILL RUN AFTER THE FIRST TASK HAS COMPLETED 
}, 0);
console.log(3);

